FROM python:3.12-slim

WORKDIR /app

COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ /app/api
COPY ui /app/ui/

COPY src/infrastructure/ /app/src/infrastructure/
COPY src/mobilenetv2ssd/ /app/src/mobilenetv2ssd/

ENV PYTHONPATH=/app/src

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]